version: '3.9'
services:
  maria_db:
    image: "mariadb:latest"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: telepone
      MYSQL_USER: usertelepone
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

volumes:
  mariadb-data: